apiVersion: batch/v1
kind: Job
metadata:
  name: training-cpu
  namespace: mlops
  labels:
    app: training-cpu
    project: proj06
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: training-cpu
        project: proj06
    spec:
      restartPolicy: Never
      containers:
        - name: training-cpu
          image: ghcr.io/riyampatel2001/mlops-project-proj06/training-cpu:latest
          resources:
            requests:
              cpu: "2000m"
              memory: "4Gi"
            limits:
              cpu: "4000m"
              memory: "8Gi"
          envFrom:
            - secretRef:
                name: proj06-env
          env:
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                secretKeyRef:
                  name: mlflow-uri
                  key: uri
            - name: DATA_PATH
              value: "/data/processed"
            - name: MODEL_OUTPUT_PATH
              value: "/models"
          volumeMounts:
            - name: data-storage
              mountPath: /data
            - name: model-storage
              mountPath: /models
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: data-pvc
        - name: model-storage
          persistentVolumeClaim:
            claimName: serving-models-pvc
