apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: mlops
  labels:
    app: adminer
    project: proj06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
        project: proj06
    spec:
      initContainers:
        - name: prepare-php-sessions
          image: busybox:1.36
          command:
            - sh
            - -c
            - mkdir -p /sessions && chmod 1733 /sessions
          volumeMounts:
            - name: php-sessions
              mountPath: /sessions
      containers:
        - name: adminer
          image: adminer:4.8.1-standalone
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: postgres
          volumeMounts:
            - name: php-sessions
              mountPath: /var/lib/php/sessions
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      volumes:
        - name: php-sessions
          emptyDir: {}
