apiVersion: v1
kind: Service
metadata:
  name: embedding-service
  namespace: mlops
  labels:
    app: embedding-service
    project: proj06
spec:
  selector:
    app: embedding-service
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
  type: ClusterIP
