apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifacts-pvc
  namespace: mlops
  labels:
    project: proj06
spec:
  storageClassName: ""
  volumeName: mlflow-artifacts-pv-vdb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
