apiVersion: batch/v1
kind: Job
metadata:
  name: feature-computation
  namespace: mlops
  labels:
    app: feature-computation
    project: proj06
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: feature-computation
        project: proj06
    spec:
      restartPolicy: Never
      containers:
        - name: feature-computation
          image: ghcr.io/riyampatel2001/mlops-project-proj06/feature-computation:latest
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          env:
            - name: DATA_INPUT_PATH
              value: "/data/processed"
            - name: DATA_OUTPUT_PATH
              value: "/data/features"
          volumeMounts:
            - name: data-storage
              mountPath: /data
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: data-pvc
