apiVersion: batch/v1
kind: Job
metadata:
  name: training-gpu
  namespace: mlops
  labels:
    app: training-gpu
    project: proj06
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: training-gpu
        project: proj06
    spec:
      restartPolicy: Never
      containers:
        - name: training-gpu
          image: ghcr.io/riyampatel2001/mlops-project-proj06/training-gpu:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "2000m"
              memory: "8Gi"
            limits:
              cpu: "4000m"
              memory: "16Gi"
              nvidia.com/gpu: "1"
          envFrom:
            - secretRef:
                name: proj06-env
          env:
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                secretKeyRef:
                  name: mlflow-uri
                  key: uri
            - name: DATA_PATH
              value: "/data/processed"
            - name: MODEL_OUTPUT_PATH
              value: "/models"
          volumeMounts:
            - name: data-storage
              mountPath: /data
            - name: model-storage
              mountPath: /models
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: data-pvc
        - name: model-storage
          persistentVolumeClaim:
            claimName: serving-models-pvc
