mlflow:
  tracking_uri: "http://129.114.26.157:30500 "
  experiment_name: "layer2-evaluation"

minio:
  endpoint: "http://10.43.4.193:9000"
  bucket: "data"
  object: "processed/train.csv"

data:
  train_csv: "http://10.43.4.193:9000/data/processed/train.csv"   # kept for reference

layer1:
  model_uri: "runs:/e99c0f7fe5554fd584c9efd2162f5572/fasttext.bin"             # replace with your fastText MLflow run URI
  model_version: "fasttext-v1"

layer2:
  model_name: "sentence-transformers/all-mpnet-base-v2"
  max_length: 128
  k: 5
  similarity_threshold: 0.85
  min_history: 10
  store_path: "artifacts/user_store.pkl"        # relative to model_pipeline/layer2/

layer3:
  eps: 0.15              # DBSCAN epsilon (cosine distance, not similarity)
  min_samples: 3         # minimum cluster size
  store_path: "artifacts/user_store.pkl"   # same as layer2