mlflow:
  tracking_uri: "http://129.114.25.143:30500 "
  experiment_name: "layer2-evaluation"

minio:
  endpoint: "http://minio.mlops.svc.cluster.local:9000"
  bucket: "data"
  object: "processed/train.csv"

data:
  train_csv: "http://129.114.25.143:30900/data/processed/train.csv"   # kept for reference

layer1:
  model_uri: "runs:/85b08fba7b6f4ad183702adad093b673/fasttext.bin"   # MLflow model artifact URI for layer 1 model
  model_version: "fasttext-v1"

layer2:
  model_name: "sentence-transformers/all-mpnet-base-v2"
  max_length: 128
  k: 5
  similarity_threshold: 0.75
  min_history: 10
  store_path: "/app/artifacts/user_store.pkl"    # PVC mounted at /app/artifacts

layer3:
  eps: 0.15              # DBSCAN epsilon (cosine distance, not similarity)
  min_samples: 3         # minimum cluster size
  store_path: "/app/artifacts/user_store.pkl"   # PVC mounted at /app/artifacts

postgres:
  dsn: "postgresql://mlops_user:mlops_pass@postgres.mlops.svc.cluster.local:5432/mlops"