apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: mlops
  labels:
    project: proj06
spec:
  storageClassName: ""
  volumeName: postgres-pv-vdb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
