apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: mlops
  labels:
    project: proj06
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifacts-pvc
  namespace: mlops
  labels:
    project: proj06
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
