apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-uri
  namespace: mlops
spec:
  encryptedData:
    MLFLOW_TRACKING_URI: AgDJEAf5tp/zY3NHIrfu3GVFKuD2O/yUC9Vg6hNFxGBCXHT4oF6mElAIu6tVfqxu44vQAF8XUJ4ZJfBtmnfMDUnDfZLuEAgzpCQ03FEVXnh3n0L8zs3JtWhA3Qns4IHf2XZiD1lPRzjkCmR0LC/tnUOhDyfQ4i0EY4v12CbUHeV1hIafthBRvTlcxKMSiP8Ct5koD6Rm+tsUSt0fiDSthPu/o0NlK+hevOdLA0yLn0bCdse4VqIAwAjfdfpbnIUwyAxeW9/dVJqBk6wyXKxWl7wAfSd45V1KECG3uuxwnURD0qJMgUnD9ESf6N+QJnyzVqLBqKTC3NuMk8G/TTew5wcOSbYpo8O3oiA2W0it8agBDoDmkuErx3ycHvkNgXQw35UggPLmGGn5VDMaNyfc81Jhn0LktOzmt9IS+x/JoIh/wHQ2ZX9s9/iTvapG3vCUDncpasx9j0XfreS/BOsPoW7NHS4udSF/Yx16aQQvzCHJfTFQVdUQuwI9GqjdYmOSPkrnpnFmpsyONVWBRdn+aSR1iRyPdtbx7yxWTMSnsy6Vx1jeAULq8L6iU3KYb4mZu31nzWnc7Wi2diyvFDmDa21onXdeMEo71Q/auHIQaPAVpz3hP8E52+6bzzGJ5muW6Es2RP9m9VWKrHjZwNmdZHcPoIdg4PKX44A1gcMixDCmSd/ydoGIdDrkjICsnyvxKCNMX1vPRzngrEoAKpGUiRrLzMrCEDkXv/pRT6t7
