services:
  jupyter:
    build:
      context: ..
      dockerfile: docker/Dockerfile.jupyter-eval
    ports:
      - "8888:8888"
    volumes:
      - ../evaluation:/home/jovyan/work/evaluation
      - ../scripts:/home/jovyan/work/scripts
      - ../models:/home/jovyan/work/models
      - ../data:/home/jovyan/work/data
    shm_size: "16g"
    container_name: jupyter_eval

  jupyter_gpu:
    build:
      context: ..
      dockerfile: docker/Dockerfile.jupyter-eval-gpu
    ports:
      - "8889:8888"
    volumes:
      - ../evaluation:/home/jovyan/work/evaluation
      - ../scripts:/home/jovyan/work/scripts
      - ../models:/home/jovyan/work/models
      - ../data:/home/jovyan/work/data
    shm_size: "16g"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    container_name: jupyter_eval_gpu

  jupyter_openvino:
    build:
      context: ..
      dockerfile: docker/Dockerfile.jupyter-eval-openvino
    ports:
      - "8890:8888"
    volumes:
      - ../evaluation:/home/jovyan/work/evaluation
      - ../scripts:/home/jovyan/work/scripts
      - ../models:/home/jovyan/work/models
      - ../data:/home/jovyan/work/data
    shm_size: "16g"
    container_name: jupyter_eval_openvino
